### ISSUE TITLE
Wrong message Error for broken import

### ISSUE THREAD

**Issue by gabbork** [20tab/upy#18]
Loading the admin a broken import caused this error:

``` python
django.core.exceptions.ImproperlyConfigured: Error importing middleware 
upy.contrib.tree.middleware.publications: "cannot import name ImageGalleryLink"
```

but the error was not in **upy.contrib.tree.middleware.publications**, but in **my_gallery_app/my_gallery_admin**

**Comment by 20tab** [comment]
bug not found
