### ISSUE TITLE
publication url

### ISSUE THREAD

**Issue by gabbork** [20tab/upy#26]
the publication url in G11n contrib changes the behavior if it includes **http://** or not.
It should be smarter and recognize the right url with or without the **http://** or **www**.

For example:
in my local application:
- with url **http://127.0.0.1:8080** it fails (no favicon)
- with url **127.0.0.1:8080** it works (I can see the favicon)

maybe we should validate it on insert or just remove http:// in any when checking the url.

**Comment by rafleze** [comment]
fixed
