### ISSUE TITLE
middleware.publication eating errors...

### ISSUE THREAD

**Issue by gabbork** [20tab/upy#33]
"probably" if something goes wrong in some import somewhere in the applications, upy gives always the same error

``` python
django.core.exceptions.ImproperlyConfigured: Error importing middleware upy.contrib.tree.middleware.publications: "No module named [my.model.not.found]"
```

**Comment by rafleze** [comment]
django.contrib.admin.auto_discover() does not found module named [my.model.not.found]
Surely because some registered models don't exist
