### ISSUE TITLE
tree static manager improvement

### ISSUE THREAD

**Issue by gabbork** [20tab/upy#34]
Both tree.js and tree.css models should have a new field after **file_name**, like **file_url**
- file_name is no more mandatory
- file_url is not mandatory and it's a charfield where you can put the url of your file (local or remote) if it's not listed in the file_name select.
- the validation should check that you can not fill both file_name and file_url fields, but you have to fill at least one of them.

so you can easily manage your css and js file in upy admin, including them into templates or structures, even if they are not in your static directory 

_with this new feature upy will be no more backward compatible_

**Comment by rafleze** [comment]
it's obsolete
