### ISSUE TITLE
easy cms

### ISSUE THREAD

**Issue by gabbork** [20tab/upy#41]
In order to create a very easy cms (maybe a new contrib to activate if **contrib.tree** and **contrib.staticpage** are on), we can create a single proxymodel to **Node**, called for example **StaticNode**, to let a 'common' user managing the tree and adding staticpages to it.
The Node model should have a way to _lock_ the position, maybe a boolean, and to define the _max_depth_ of his children.
So the programmer can create the entire tree and put all the pages/views ecc, and then lock the main node in order to don't permit the user to broke something.
The user can just create, delete or update **StaticNode** (that refer to staticpage view and template by default), can change the **Node** position only if it's not locked, can add new children to a node only if the max depth allows it.

For example:

root
- \- - main_menu
- \- - - - - - - - news
- \- - - - - - - - events
- \- - aside_menu
- \- - - - - - - - user_content_1
- \- - - - - - - - user_content_2
- \- - - - - - - - - - - - - - user_content_3
  ecc

root, main_menu, aside_menu should be locked. News and Events are not static, so the user cannot update them, all the rest (user content) would be static content, so changeable by the user

**Comment by rafleze** [comment]
@gabbork in how many cases we really need it???

**Comment by rafleze** [comment]
I close the issue because I think that this cms is not necessary.
Reopen if you still think that we need a cms
