### ISSUE TITLE
g11n order_by

### ISSUE THREAD

**Issue by gabbork** [20tab/upy#61]
G11nBase objects usually have to be ordered by a G11n related object attribute, like:

``` python
class Example(G11nBase):
    image = ImageField(...)
    class Meta:
        ordering = ??? self.g11n.name

class ExampleG11n(G11n):
    name = Charfield(...)
    class Meta:
        ordering = ['name']
```

We have to provide a simple api to do it.

**Comment by rafleze** [comment]
now g11nobjects manager can order by g11nmodel field
