### ISSUE TITLE
manage.py createsuperuser doesn't validate g11n models

### ISSUE THREAD

**Issue by gabbork** [20tab/upy#66]
[...]
  File "/WinScripts/venvs/venv_upy019_django15/lib/python2.6/site-packages/django/core/management/base.py", line 284, in validate
    raise CommandError("One or more models did not validate:\n%s" % error_text)
django.core.management.base.CommandError: One or more models did not validate:
tree.publicationextended: 'publication' has a relation with model <class 'upy.contrib.g11n.models.Publication'>, which has either not been installed or is abstract.
tree.nodeg11n: 'publication' has a relation with model <class 'upy.contrib.g11n.models.Publication'>, which has either not been installed or is abstract.
tree.nodeg11n: 'language' has a relation with model <class 'upy.contrib.g11n.models.Language'>, which has either not been installed or is abstract.
tree.pageg11n: 'publication' has a relation with model <class 'upy.contrib.g11n.models.Publication'>, which has either not been installed or is abstract.
tree.pageg11n: 'language' has a relation with model <class 'upy.contrib.g11n.models.Language'>, which has either not been installed or is abstract.

**Comment by rafleze** [comment]
g11n doesn't exist yes
